### PR TITLE
use the new collections.abc when possible

### LINKED ISSUE #52: handle collections deprecation
```
/pathlib2/__init__.py:15: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
    from collections import Sequence

```

### PR DESCRIPTION
**Pull request by gaborbernat**
Resolves #52

### CODE REVIEW

**Comment by mcmtroffaes** [comment]
Looks good - thanks!

**Comment by gaborbernat** [comment]
Can we release this, please? thanks!

**Comment by mcmtroffaes** [comment]
Sure, I've published a release just now.

**Comment by gaborbernat** [comment]
Thanks!

**Pull request merged**
