### PR TITLE
Fix wheel to properly handle conditional scandir dependency.

### PR DESCRIPTION
**Pull request by mcmtroffaes**
... see issue #20.

### CODE REVIEW

**Comment by mcmtroffaes** [comment]
@AvdN Can you check if this branch fixes the problem for you?

**Comment by AvdN** [comment]
I downloaded the branch as zip, created the wheel, uploaded it to my devpi server and adapted my Dockerfile to take packages from there:
```
Step 11 : RUN /tmp/scandirtest/bin/pip install --pre 'pathlib2>=2.2.0'
 ---> Running in 059f10eed4e5
Collecting pathlib2>=2.2.0
  Downloading http://192.168.0.101:4040/anthon/dev/+f/ad9/649e3877aea86/pathlib2-2.2.1a0-py2.py3-none-any.whl
Collecting six (from pathlib2>=2.2.0)
  Downloading six-1.10.0-py2.py3-none-any.whl
Installing collected packages: six, pathlib2
Successfully installed pathlib2-2.2.1a0 six-1.10.0
 ---> 27fba4993e64
Removing intermediate container 059f10eed4e5
Successfully built 27fba4993e64
```

So that does work fine, thanks for the quick fix. If you let me know when you upload this to pypi, I'll test it what that version as well and close #20

**Comment by mcmtroffaes** [comment]
Thanks for confirming that this works! I'll upload a new version on pypi momentarily.

**Comment by mcmtroffaes** [comment]
Closes #20.

**Pull request merged**
