### PR TITLE
os.compat (clbarnes remix)

### PR DESCRIPTION
**Pull request by clbarnes**
# WIP

- Drop support for python versions which are EOL (i.e. 2.6 and 3.<4)
- Use tox to control testing
- Switch from the unicode compile script to just copying the test file with `from __future__ import unicode_literals` at the top
- Include a Makefile which controls the above and the testing
- `context.py` still exists but doesn't do the path mangling: `make test` ensures that `pathlib2` is installed (in develop/ editable mode)

### CODE REVIEW

**Comment by clbarnes** [comment]
Locally, I get 4 unicode-related failures in the py2 builds.

**Comment by mcmtroffaes** [comment]
Just an update here: I've reviewed the directory refactoring and I'm happy to report that this has (finally!) landed in develop. I appreciate the work you've done on this, but the pull request is simply too large for review, and does too many things at once, so there's no way I will merge this as such even after resolving conflicts. However, some of your relevant commits have been merged. I haven't yet fully reviewed the actual os shim code (I'll probably handle this in a separate pull request).

**Comment by mcmtroffaes** [comment]
It's been a while that there has been activity here. Is anything still up for merging from this PR?

**Comment by mcmtroffaes** [comment]
Closing due to inactivity. Once more, thanks for your useful contributions through this PR that did make it into the main branch!

**Comment by clbarnes** [comment]
Sorry I didn't have time to loop back to this! You're right that it ended up doing too many things, it ended up being more exploratory than anything else; I'm glad some of it was of use though.

**Comment by mcmtroffaes** [comment]
No worries! Thanks for taking the effort to come back to me. :+1:

**Pull request closed without merging**
