### PR TITLE
remove obsolescence notice

### PR DESCRIPTION
**Pull request by graingert**

### CODE REVIEW

**Comment by mcmtroffaes** [comment]
I'm very sorry, but I have no intention to keep this up to date.

**Comment by graingert** [comment]
@mcmtroffaes would you be interested in moving this project to jazzband so it can continue as a backport library for supported Python versions (similar to https://github.com/jazzband/contextlib2 )?

**Comment by mcmtroffaes** [comment]
Sure, if pathlib2 would be welcomed there, that would be great! Probably needs some updates to the readme, setup, etc. I'll see if I can initiate the transfer.

**Comment by mcmtroffaes** [comment]
I tried but for some reason it failed. I think I have to be an organisation member first?

**Comment by mcmtroffaes** [comment]
I think it's done now. 🎉

**Pull request closed without merging**
